matrix:
  include:
    - dist: xenial
      language: python
      python:
        - "3.6"
      # command to install dependencies
      before_script:
        - cd cinderServer
      install:
        - sudo apt-get install unixodbc unixodbc-dev
        - pip install -r requirements.txt
      # command to run tests
      script:
        - pytest

    - language: android
      android:
        components:
          # Uncomment the lines below if you want to
          # use the latest revision of Android SDK Tools
          # - tools
          # - platform-tools

          # The BuildTools version used by your project
          - build-tools-26.0.2

          # The SDK version used to compile your project
          - android-26

          # Additional components
          - extra-google-google_play_services
          - extra-google-m2repository
          - extra-android-m2repository

          # Specify at least one system image,
          # if you need to run emulator(s) during your tests
          - sys-img-x86-android-26
          - sys-img-armeabi-v7a-android-17
        # Emulator Management: Create, Start and Wait
      before_script:
        - cd Cinder/Cinder
        - chmod +x gradlew
      install:
        - ./gradlew build connectedCheck
