matrix:
  include:
    - dist: xenial
      language: python
      python:
        - "3.6"
      # command to install dependencies
      before_script:
        - cd cinderServer
      install:
        - sudo apt-get install unixodbc unixodbc-dev
        - pip install -r requirements.txt
      # command to run tests
      script:
        - pytest
