# Generated by Django 2.1.2 on 2018-10-20 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('school', models.CharField(max_length=100)),
                ('courses', models.TextField()),
                ('preferences', models.TextField()),
                ('interests', models.TextField()),
            ],
        ),
    ]
