# Generated by Django 2.1.2 on 2018-11-17 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20181020_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='currentHash',
            field=models.CharField(default='abcedfghijklmnop', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='loggedin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='password',
            field=models.CharField(default='1234', max_length=100),
        ),
    ]
