# Generated by Django 2.1.3 on 2018-11-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_auto_20181116_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='deviceID',
            field=models.TextField(default='abc123abc'),
        ),
    ]
