# Generated by Django 2.1.3 on 2018-11-25 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_profile_deviceid'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notification',
            field=models.BooleanField(default=True),
        ),
    ]
