# Generated by Django 2.1.3 on 2018-11-21 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Matchmaking', '0004_auto_20181024_1439'),
        ('userprofile', '0003_auto_20181116_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('groupMessage', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='date sent')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='group', to='Matchmaking.Match')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reciever', to='Matchmaking.Match')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sender', to='userprofile.Profile')),
            ],
        ),
    ]
