# Generated by Django 2.1.3 on 2018-11-25 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Matchmaking', '0005_auto_20181122_2106'),
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='group',
        ),
        migrations.RemoveField(
            model_name='message',
            name='groupMessage',
        ),
        migrations.RemoveField(
            model_name='message',
            name='match',
        ),
        migrations.AddField(
            model_name='message',
            name='matchID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='matches', to='Matchmaking.Match'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
