# Generated by Django 2.1.3 on 2018-11-25 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_auto_20181124_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='matchID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='matches', to='Matchmaking.Match'),
        ),
    ]
